apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-dotnet
spec:
  selector:
    matchLabels:
      app: ado-dotnet
  replicas: 1
  template:
    metadata:
      labels:
        app: ado-dotnet
    spec:
      containers:
        - name: ado-dotnet
          image: cr00cfaroregistry.azurecr.io/ado-openshift/ado-dotnet
          ports:
            - containerPort: 8080

